// Reserved username yang diblokir (PRD Lampiran A.2). Daftar dikelola terpusat
// sebagai konstanta sehingga dapat diperluas tanpa perubahan skema database.
// Pengecekan bersifat case-insensitive: nilai selalu dinormalkan ke huruf kecil.

const RESERVED_USERNAME_GROUPS = {
  "Peran & Administrasi": [
    "admin",
    "administrator",
    "superadmin",
    "super_admin",
    "superuser",
    "owner",
    "manager",
    "moderator",
    "root",
    "master",
    "system",
    "sys",
    "kasir",
    "cashier",
    "staff",
    "staf",
    "pegawai",
  ],
  "Fungsi Sistem & Autentikasi": [
    "login",
    "logout",
    "register",
    "registration",
    "signin",
    "signup",
    "daftar",
    "masuk",
    "auth",
    "authorize",
    "session",
    "password",
    "sandi",
    "reset",
    "verify",
    "verifikasi",
    "aktivasi",
    "api",
    "webhook",
    "callback",
    "oauth",
    "sso",
    "token",
    "otp",
  ],
  "Halaman & Fitur Aplikasi": [
    "dashboard",
    "home",
    "beranda",
    "profile",
    "profil",
    "akun",
    "account",
    "settings",
    "pengaturan",
    "help",
    "bantuan",
    "support",
    "contact",
    "kontak",
    "info",
    "about",
    "scan",
    "voucher",
    "promo",
    "reward",
    "poin",
    "points",
    "loyalty",
    "member",
    "membership",
    "diskon",
    "kupon",
    "barcode",
    "qrcode",
  ],
  "Brand & Identitas Resmi": [
    "donjun",
    "donjundonat",
    "donjun_donat",
    "donjun.donat",
    "official",
    "resmi",
    "brand",
    "store",
    "toko",
    "outlet",
    "gerai",
  ],
  "Umum & Teknis": [
    "test",
    "testing",
    "demo",
    "sample",
    "contoh",
    "user",
    "username",
    "customer",
    "pelanggan",
    "guest",
    "tamu",
    "anonymous",
    "null",
    "undefined",
    "mail",
    "email",
    "smtp",
    "sms",
    "whatsapp",
    "bot",
    "cron",
    "server",
    "database",
  ],
} as const;

export const RESERVED_USERNAMES: ReadonlySet<string> = new Set(
  Object.values(RESERVED_USERNAME_GROUPS).flat(),
);

export function isReservedUsername(value: string): boolean {
  return RESERVED_USERNAMES.has(value.trim().toLowerCase());
}
